version: '3.7'

services:

  # OpenSearch Docker Images: https://hub.docker.com/r/opensearchproject/opensearch/
  opensearch:
    image: opensearchproject/opensearch:1.3.13
    environment:
      - node.name=opensearch01
      - discovery.type=single-node
      - "DISABLE_SECURITY_PLUGIN=true"
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=docker-cluster
      - bootstrap.system_call_filter=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200

  opensearch-seed:
    build: ../.
    depends_on:
      - opensearch
    environment:
      - OPENSEARCH_URL=http://opensearch:9200
      - INDEX_NAME=my-index
    volumes:
      - ./my-custom-index-settings.json:/seed/index-settings.json
      - ./my-custom-index-bulk-payload.json:/seed/index-bulk-payload.json


volumes:
  opensearch-data:
    driver: local